### ISSUE TITLE
Enchant

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdla-io-hdf#2]
- [x] Travis-CI https://travis-ci.org/PDLPorters/pdla-io-hdf (https://travis-ci.org/profile/PDLPorters)
- [x] Appveyor CI (https://ci.appveyor.com/)
- [x] Coveralls https://coveralls.io/r/PDLPorters/pdla-io-hdf (https://coveralls.io/repos/new?name=PDLPorters)
- [x] IRC notifications (handled by devops `enchant` script)

**Comment by mohawk2** [comment]
IRC notifications are no more. AppVeyor is enabled, but I don't know of an easy way to get HDF onto Windows. It may come down to `Alien::HDF4` becoming able to download/build/install it.
